version: "3"
services:
  vue:
    build:
      context: ./docker/vue
    container_name: front-vue
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: sh -c "cd reco-share && yarn install && yarn serve"

  go:
    build:
      context: ./docker/go
    container_name: backend-go
    ports:
      - 8082:8082
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    command: fresh

  nginx:
    image: nginx
    depends_on:
      - go
    container_name: nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
