version: "3"
services:
  vue:
    build:
      context: ./docker/vue
    container_name: front-vue
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: sh -c "cd reco-share && yarn install && yarn serve"

  go:
    build:
      context: ./docker/go
    container_name: backend-go
    ports:
      - 8082:8082
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    command: fresh

  nginx:
    image: nginx
    depends_on:
      - go
    container_name: nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql:5.7
    container_name: db-mysql
    # networks:
    #   app_net:
    #     ipv4_address: 172.30.0.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recoshare_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
